import gallery1 from 'assets/photo/gallerylist/gallery01.png';
import gallery2 from 'assets/photo/gallerylist/gallery02.png';
import gallery3 from 'assets/photo/gallerylist/gallery03.png';
import gallery4 from 'assets/photo/gallerylist/gallery04.png';
import gallery5 from 'assets/photo/gallerylist/gallery05.png';
import gallery6 from 'assets/photo/gallerylist/gallery06.png';

const GALLERY_DATAS = [
  {
    title: '2024 졸업식',
    author: '작성자1',
    time: '1분 전',
    src: [gallery1, gallery2, gallery6],
    alt: '2024-졸업식',
    view: 182,
    count: 3,
  },
  {
    title: 'umc 해커톤',
    author: '작성자2',
    time: '5시간 전',
    src: [gallery2, gallery5],
    alt: 'umc-해커톤',
    view: 182,
    count: 2,
  },
  {
    title: '단체 야구 관람',
    author: '작성자3',
    time: '6시간 전',
    src: [gallery3, gallery6],
    alt: '단체 야구 관람',
    view: 182,
    count: 2,
  },
  {
    title: '새내기 캠퍼스 투어',
    author: '작성자4',
    time: '2023.12.18',
    src: [gallery4, gallery2, gallery5],
    alt: '새내기 캠퍼스 투어',
    view: 182,
    count: 3,
  },
  {
    title: '2024 졸업식',
    author: '작성자5',
    time: '2023.11.14',
    src: [gallery1, gallery2, gallery6],
    alt: '2024-졸업식',
    view: 182,
    count: 3,
  },
  {
    title: '학교 사진',
    author: '작성자6',
    time: '2023.11.14',
    src: [gallery4, gallery2],
    alt: '학교 사진',
    view: 182,
    count: 2,
  },
  {
    title: '12차 회의 사진',
    author: '작성자7',
    time: '2023.11.14',
    src: [gallery5, gallery2],
    alt: '12차 회의 사진',
    view: 182,
    count: 2,
  },
  {
    title: '단체 축구 관람',
    author: '작성자8',
    time: '2023.11.14',
    src: [gallery6, gallery3],
    alt: '단체 축구 관람',
    view: 182,
    count: 2,
  },
  {
    title: '2024 졸업식',
    author: '작성자1',
    time: '1분 전',
    src: [gallery1, gallery2, gallery6],
    alt: '2024-졸업식',
    view: 182,
    count: 3,
  },
  {
    title: 'umc 해커톤',
    author: '작성자2',
    time: '5시간 전',
    src: [gallery2, gallery5],
    alt: 'umc-해커톤',
    view: 182,
    count: 2,
  },
  {
    title: '단체 야구 관람',
    author: '작성자3',
    time: '6시간 전',
    src: [gallery3, gallery6],
    alt: '단체 야구 관람',
    view: 182,
    count: 2,
  },
  {
    title: '새내기 캠퍼스 투어',
    author: '작성자4',
    time: '2023.12.18',
    src: [gallery4, gallery2, gallery5],
    alt: '새내기 캠퍼스 투어',
    view: 182,
    count: 3,
  },
  {
    title: '2024 졸업식',
    author: '작성자5',
    time: '2023.11.14',
    src: [gallery1, gallery2, gallery6],
    alt: '2024-졸업식',
    view: 182,
    count: 3,
  },
  {
    title: '학교 사진',
    author: '작성자6',
    time: '2023.11.14',
    src: [gallery4, gallery2],
    alt: '학교 사진',
    view: 182,
    count: 2,
  },
  {
    title: '12차 회의 사진',
    author: '작성자7',
    time: '2023.11.14',
    src: [gallery5, gallery2],
    alt: '12차 회의 사진',
    view: 182,
    count: 2,
  },
  {
    title: '단체 축구 관람',
    author: '작성자8',
    time: '2023.11.14',
    src: [gallery6, gallery3],
    alt: '단체 축구 관람',
    view: 182,
    count: 2,
  },
  {
    title: '2024 졸업식',
    author: '작성자1',
    time: '1분 전',
    src: [gallery1, gallery2, gallery6],
    alt: '2024-졸업식',
    view: 182,
    count: 3,
  },
  {
    title: 'umc 해커톤',
    author: '작성자2',
    time: '5시간 전',
    src: [gallery2, gallery5],
    alt: 'umc-해커톤',
    view: 182,
    count: 2,
  },
  {
    title: '단체 야구 관람',
    author: '작성자3',
    time: '6시간 전',
    src: [gallery3, gallery6],
    alt: '단체 야구 관람',
    view: 182,
    count: 2,
  },
  {
    title: '새내기 캠퍼스 투어',
    author: '작성자4',
    time: '2023.12.18',
    src: [gallery4, gallery2, gallery5],
    alt: '새내기 캠퍼스 투어',
    view: 182,
    count: 3,
  },
  {
    title: '2024 졸업식',
    author: '작성자5',
    time: '2023.11.14',
    src: [gallery1, gallery2, gallery6],
    alt: '2024-졸업식',
    view: 182,
    count: 3,
  },
  {
    title: '학교 사진',
    author: '작성자6',
    time: '2023.11.14',
    src: [gallery4, gallery2],
    alt: '학교 사진',
    view: 182,
    count: 2,
  },
  {
    title: '12차 회의 사진',
    author: '작성자7',
    time: '2023.11.14',
    src: [gallery5, gallery2],
    alt: '12차 회의 사진',
    view: 182,
    count: 2,
  },
  {
    title: '단체 축구 관람',
    author: '작성자8',
    time: '2023.11.14',
    src: [gallery6, gallery3],
    alt: '단체 축구 관람',
    view: 182,
    count: 2,
  },
];

export { GALLERY_DATAS };
